# Stationary Iterative Methods 

In [ ]:
import torch

In [62]:
def generate_tridiagonal(n):
    c = torch.tensor([-1,0,1]).repeat(n)
    r = torch.arange(n).repeat_interleave(3)
    cr = c + r
    rows = r[1:-1]
    cols = cr[1:-1]
    vals = torch.tensor([-0.5, 5 ,-1.5]).repeat(n)[1:-1]
    Ai = torch.stack([rows, cols])
    A = torch.sparse_coo_tensor(Ai, vals, (n,n))
    return A

In [78]:
n = 5
A = generate_tridiagonal(5)
A

tensor(indices=tensor([[0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4],
                       [0, 1, 0, 1, 2, 1, 2, 3, 2, 3, 4, 3, 4]]),
       values=tensor([ 5.0000, -1.5000, -0.5000,  5.0000, -1.5000, -0.5000,
                       5.0000, -1.5000, -0.5000,  5.0000, -1.5000, -0.5000,
                       5.0000]),
       size=(5, 5), nnz=13, layout=torch.sparse_coo)

In [83]:
Ad = A.to_dense()
Ad 

tensor([[ 5.0000, -1.5000,  0.0000,  0.0000,  0.0000],
        [-0.5000,  5.0000, -1.5000,  0.0000,  0.0000],
        [ 0.0000, -0.5000,  5.0000, -1.5000,  0.0000],
        [ 0.0000,  0.0000, -0.5000,  5.0000, -1.5000],
        [ 0.0000,  0.0000,  0.0000, -0.5000,  5.0000]])

In [84]:
torch.linalg.det(Ad)

tensor(2758.4375)

In [74]:
sI = Ad.diagonal()
B = torch.diag_embed(sI) - Ad
B

tensor([[0.0000, 0.0005, 0.0000, 0.0000, 0.0000],
        [0.0002, 0.0000, 0.0005, 0.0000, 0.0000],
        [0.0000, 0.0002, 0.0000, 0.0005, 0.0000],
        [0.0000, 0.0000, 0.0002, 0.0000, 0.0005],
        [0.0000, 0.0000, 0.0000, 0.0002, 0.0000]])

In [75]:
sI

tensor([0.0018, 0.0018, 0.0018, 0.0018, 0.0018])

In [76]:
rho = torch.linalg.eigvals(B).abs().max()
rho

tensor(0.0005)