# More on SVD ...

References for Golub and Khan SVD algorithm:
* [Stanford notes](https://web.stanford.edu/class/cme335/lecture6.pdf)
* [Numerical recipes C implementation](https://github.com/JohnWStockwellJr/SeisUnix/blob/master/src/cwp/lib/svd.c)


In [11]:
import torch
A_ = torch.randn(5, 5)
A = A_ + A_.t()
A

tensor([[ 2.4646, -0.3774, -0.9269,  1.5665, -0.7283],
        [-0.3774,  2.8627,  0.6433,  0.0870,  0.4456],
        [-0.9269,  0.6433, -1.6502,  1.3867,  0.8651],
        [ 1.5665,  0.0870,  1.3867,  2.3124, -0.1294],
        [-0.7283,  0.4456,  0.8651, -0.1294, -0.2182]])

In [20]:
eigenvals, eigenvectors = torch.linalg.eigh(A, 'L')
eigenvals

tensor([-2.6715, -0.4328,  1.5487,  3.2105,  4.1165])

In [21]:
eigenvectors

tensor([[-0.2167, -0.3538,  0.5451,  0.0256, -0.7281],
        [ 0.0627,  0.0942,  0.4579, -0.8460,  0.2486],
        [-0.8848, -0.0919, -0.3688, -0.2688,  0.0224],
        [ 0.3198,  0.2028, -0.5429, -0.4284, -0.6152],
        [ 0.2531, -0.9035, -0.2500, -0.1670,  0.1707]])

In [23]:
torch.dist(A, eigenvectors @ eigenvals.diag_embed() @ eigenvectors.t())

tensor(3.2437e-06)

### Exercise
**(1)** Compute the SVD decomposition of a real symmetric matrix using the eigendecomposition
**(2)** and vice-versa ...