In [1]:
import torch

In [24]:
a = torch.rand(5)
a

tensor([0.3354, 0.9282, 0.3346, 0.7336, 0.3097])

In [25]:
a.requires_grad

False

In [26]:
a = a.requires_grad_()

In [27]:
a.requires_grad

True

In [28]:
b = torch.randn(5)
b = b.requires_grad_()

In [30]:
v_1 = a

In [31]:
v0 = b

In [32]:
v2 = torch.log(v_1)
v3 = v_1 * v0

In [33]:
v4 = v2 + v3
v5 = torch.sin(v0)
v6 = v4 - v5

In [34]:
v6

tensor([-1.0521, -0.0566, -0.5892, -0.1868, -1.5987], grad_fn=<SubBackward0>)

In [35]:
v7 = v6.sum()

In [36]:
v7

tensor(-3.4833, grad_fn=<SumBackward0>)

In [37]:
gv7 = torch.autograd.grad(v7, [a,b])

In [38]:
gv7

(tensor([2.9209, 0.7325, 1.9946, 0.4627, 3.9270]),
 tensor([-0.6628, -0.0129, -0.2106,  0.1123, -0.4561]))

Differentiable programming in [science](https://github.com/grinisrit/noa/blob/master/docs/pms/differentiable_programming_pms.ipynb)