# Stationary Iterative Methods

In [2]:
import torch

## Jacobi method

[Wiki](https://en.wikipedia.org/wiki/Jacobi_method) is the reference for that.

In [3]:
def generate_tridiagonal(n, l, d, u):
    c = torch.tensor([-1,0,1]).repeat(n)
    r = torch.arange(n).repeat_interleave(3)
    cr = c + r
    rows = r[1:-1]
    cols = cr[1:-1]
    vals = torch.tensor([l, d ,u]).repeat(n)[1:-1]
    Ai = torch.stack([rows, cols])
    A = torch.sparse_coo_tensor(Ai, vals, (n,n))
    return A

In [14]:
n = 5
A = generate_tridiagonal(5, -0.5, 2.5, -1.5)
A

tensor(indices=tensor([[0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4],
                       [0, 1, 0, 1, 2, 1, 2, 3, 2, 3, 4, 3, 4]]),
       values=tensor([ 2.5000, -1.5000, -0.5000,  2.5000, -1.5000, -0.5000,
                       2.5000, -1.5000, -0.5000,  2.5000, -1.5000, -0.5000,
                       2.5000]),
       size=(5, 5), nnz=13, layout=torch.sparse_coo)

In [10]:
Ad = A.to_dense()
Ad 

tensor([[ 2.5000, -1.5000,  0.0000,  0.0000,  0.0000],
        [-0.5000,  2.5000, -1.5000,  0.0000,  0.0000],
        [ 0.0000, -0.5000,  2.5000, -1.5000,  0.0000],
        [ 0.0000,  0.0000, -0.5000,  2.5000, -1.5000],
        [ 0.0000,  0.0000,  0.0000, -0.5000,  2.5000]])

In [19]:
eigs = torch.linalg.eigvals(Ad / 2.5)
eigs

tensor([1.6000+0.j, 0.4000+0.j, 1.0000+0.j, 0.6536+0.j, 1.3464+0.j])

In [21]:
Acsr = A.to_sparse_csr()
Acsr

tensor(crow_indices=tensor([ 0,  2,  5,  8, 11, 13]),
       col_indices=tensor([0, 1, 0, 1, 2, 1, 2, 3, 2, 3, 4, 3, 4]),
       values=tensor([ 2.5000, -1.5000, -0.5000,  2.5000, -1.5000, -0.5000,
                       2.5000, -1.5000, -0.5000,  2.5000, -1.5000, -0.5000,
                       2.5000]), size=(5, 5), nnz=13, layout=torch.sparse_csr)

In [75]:
sI

tensor([0.0018, 0.0018, 0.0018, 0.0018, 0.0018])